### Árboles de regresión

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('python-ml-course-master/datasets/boston/Boston.csv')

In [3]:
data.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [4]:
data.shape

(506, 14)

In [5]:
colnames = data.columns.values.tolist()
predictors = colnames[:13]
target = colnames[13]
X = data[predictors]
Y = data[target]

In [6]:
from sklearn.tree import DecisionTreeRegressor

In [7]:
regtree = DecisionTreeRegressor(min_samples_split=30,min_samples_leaf=10,random_state=0)

In [8]:
regtree.fit(X,Y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=10,
                      min_samples_split=30, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=0, splitter='best')

In [9]:
preds = regtree.predict(data[predictors])

In [10]:
data['preds'] = preds

In [11]:
data[['preds','medv']]

         preds  medv
0    22.840000  24.0
1    22.840000  21.6
2    35.247826  34.7
3    35.247826  33.4
4    35.247826  36.2
5    24.058621  28.7
6    20.811111  22.9
7    20.020833  27.1
8    20.020833  16.5
9    20.020833  18.9
10   20.020833  15.0
11   20.811111  18.9
12   20.020833  21.7
13   20.624138  20.4
14   18.750000  18.2
15   20.624138  19.9
16   20.624138  23.1
17   19.408333  17.5
18   20.292308  20.2
19   20.292308  18.2
20   14.041667  13.6
21   18.750000  19.6
22   15.628000  15.2
23   14.041667  14.5
24   15.628000  15.6
25   15.628000  13.9
26   15.628000  16.6
27   15.628000  14.8
28   18.750000  18.4
29   18.750000  21.0
..         ...   ...
476  15.628000  16.7
477  12.630000  12.0
478  13.922222  14.6
479  20.783333  21.4
480  20.783333  23.0
481  27.247826  23.7
482  28.978261  25.0
483  20.783333  21.8
484  20.783333  20.6
485  20.783333  21.2
486  19.408333  19.1
487  20.783333  20.6
488  18.112500  15.2
489  14.041667   7.0
490  14.041667   8.1
491  18.112500  13.6
492  20.783333  20.1
493  20.292308  21.8
494  20.292308  24.5
495  19.408333  23.1
496  14.041667  19.7
497  18.750000  18.3
498  20.292308  21.2
499  19.408333  17.5
500  18.750000  16.8
501  22.840000  22.4
502  20.624138  20.6
503  28.978261  23.9
504  31.170000  22.0
505  20.624138  11.9

[506 rows x 2 columns]

In [12]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
import numpy as np

In [13]:
cv = KFold(n_splits= 10, shuffle=True, random_state=1)

In [14]:
scores = cross_val_score(regtree,X,Y,scoring='neg_mean_squared_error',cv = cv, n_jobs=1)

In [15]:
score = np.mean(scores)
score

-20.107307036443846

In [16]:
list(zip(predictors,regtree.feature_importances_)) #Nivel de importancia de cada una de las variables

[('crim', 0.03421203230639308),
 ('zn', 0.0),
 ('indus', 0.0011605887788380146),
 ('chas', 0.0),
 ('nox', 0.01856163073811432),
 ('rm', 0.6308568014337028),
 ('age', 0.01725115143448847),
 ('dis', 0.0013745115995791378),
 ('rad', 0.0),
 ('tax', 0.0023698305298803803),
 ('ptratio', 0.009333247332530954),
 ('black', 0.0),
 ('lstat', 0.28488020584647283)]

### Random Forest

In [17]:
from sklearn.ensemble import RandomForestRegressor

In [32]:
forest = RandomForestRegressor(n_jobs=2, oob_score=True,n_estimators=10000) # 10000 árbolres
forest.fit(X,Y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10000,
                      n_jobs=2, oob_score=True, random_state=None, verbose=0,
                      warm_start=False)

In [33]:
data['rforest_pred']= forest.oob_prediction_

In [34]:
data[['rforest_pred','medv']]

     rforest_pred  medv
0       28.366453  24.0
1       22.668293  21.6
2       34.510475  34.7
3       34.744525  33.4
4       34.306253  36.2
5       24.058518  28.7
6       20.230948  22.9
7       17.289146  27.1
8       17.787524  16.5
9       19.777997  18.9
10      20.797157  15.0
11      20.842443  18.9
12      21.114818  21.7
13      19.923334  20.4
14      20.014995  18.2
15      20.315732  19.9
16      21.354992  23.1
17      18.353844  17.5
18      18.666027  20.2
19      19.810299  18.2
20      14.510064  13.6
21      18.537497  19.6
22      16.157597  15.2
23      15.036966  14.5
24      16.695199  15.6
25      15.759625  13.9
26      17.413343  16.6
27      15.066335  14.8
28      20.036482  18.4
29      22.885834  21.0
..            ...   ...
476     15.897442  16.7
477     13.542258  12.0
478     14.526538  14.6
479     20.168766  21.4
480     21.043500  23.0
481     28.707940  23.7
482     31.995076  25.0
483     20.233716  21.8
484     20.919130  20.6
485     21.944002  21.2
486     19.001270  19.1
487     21.447419  20.6
488     14.507458  15.2
489     13.105553   7.0
490     10.862355   8.1
491     16.094032  13.6
492     20.210259  20.1
493     19.707511  21.8
494     20.710373  24.5
495     19.410935  23.1
496     18.684902  19.7
497     20.325602  18.3
498     21.251499  21.2
499     19.765446  17.5
500     20.233090  16.8
501     24.302717  22.4
502     18.998264  20.6
503     27.646957  23.9
504     26.146206  22.0
505     20.861994  11.9

[506 rows x 2 columns]

In [35]:
data['rforest_error2'] = (data['rforest_pred']-data['medv'])**2
sum(data['rforest_error2'])/len(data)

10.177583478603363

In [36]:
forest.oob_score_

0.8794404526390056